# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'


source 'git@github.com:scalemonk/ios-podspecs-framework.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  pod 'ScaleMonkAds','0.1.1-alpha.4'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if ['RxSwift', 'Willow'].include? target.name
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end
